# Dev configurations on top of base docker.compose.yml
version: '3'

services:
  # Mongo DB here TODO

  # Server
  chat-server:
    restart: always
    build:
      context: ./
      dockerfile: ./HotReload.Dockerfile

    environment:
      PORT: 80

    volumes:
      - './server:/app/server'
      - '/usr/src/app/node_modules'

  # Chat client.
  chat-client:
    restart: always
    build:
      context: ./chat-client
      dockerfile: ./HotReload.Dockerfile
    environment:
      REACT_APP_USE_WS: 'false'
    volumes:
      - './chat-client/src:/app/src'
      - './chat-client/public:/app/public'
      - '/usr/src/app/node_modules'
    ports:
      - '35729:35729'
      - '3000:3000'

    links:
      - chat-server

  # Mongodb
  mongo:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: app
      MONGO_INITDB_DATABASE: chat-app
    volumes:
      - mongostore:/data/db

  # Web UI for mongo db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chat
      ME_CONFIG_MONGODB_ADMINPASSWORD: app

    networks:
      chat-app:

volumes:
  mongostore:
