version: '3'

services:
  # Mongo DB here TODO

  # Server
  chat-server:
    build:
      context: ./
    image: opasaarinen/chat-server
    container_name: ChatServer

    networks:
      chat-app:

  # Chat client.
  chat-client:
    build:
      context: ./chat-client
    image: opasaarinen/chat-client
    container_name: ChatClient

    networks:
      chat-app:

    links:
      - chat-server

    depends_on:
      - chat-server

networks:
  chat-app:
